version: '2'
 
services:
 
  nginx:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /certs:/etc/nginx/certs
      - /vhost:/etc/nginx/vhost.d
      - /html:/usr/share/nginx/html
    networks:
      - wp-proxy
 
  wp:
    image: wordpress:5.2.3-php7.3-apache
    restart: always
    volumes:
      - /wp-cont:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD : ${pas}
      WORDPRESS_DB_HOST     : db
      WORDPRESS_DB_USER     : wp
      WORDPRESS_DB_NAME     : wp
      VIRTUAL_HOST          : wordpress.local
    networks:
      - wp-proxy
      - wp-db
 
  db:
    image: percona:5.7.26
    restart: always
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD   : ${rpas}
      MYSQL_PASSWORD        : ${pas}
      MYSQL_USER            : wp
      MYSQL_DATABASE        : wp
    volumes:
      - db-mysql:/var/lib/mysql:rw
    networks:
      - wp-db
    
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - proms
    restart: always
  
  node-exporter:
    image: prom/node-exporter:latest
    restart: always 
    volumes: 
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - proms
  
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks: 
      - proms

networks:
  wp-proxy:
    driver: bridge
  wp-db:
    driver: bridge
  proms:

volumes:
   wp-cont:
   db-mysql:
   certs:
   vhost:
   html:
   prometheus_data:
   grafana_data:    

