apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: direct
  url: http://prom.local:9090
  editable: true
  basicAuth: false
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: true
     tlsAuthWithCACert: true
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true



